changelog:
  exclude:
    labels: [duplicate, invalid, wontfix]
  categories:
    - title: Fixes
      labels: [bug, recovery]
    - title: Improvements
      labels: [enhancement, performance]
    - title: Documentation
      labels: [documentation]
    - title: Other changes
      labels: ['*']
