#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { appendFileSync } from "node:fs";

const controller="surface-export-controller", config="/clusterio/tokens/config-control.json";
const source="clusterio-host-1-instance-1", destination="clusterio-host-2-instance-1";
const prefix="inserter-lab-b-", notebook="tests/inserter-lab/NOTEBOOK.md";
const allowed=["b1","b2","b3","b4"];
let sections=[...allowed], resetOnly=false, noNotebook=false;
for(let i=2;i<process.argv.length;i+=1){const a=process.argv[i];if(a==="--reset")resetOnly=true;else if(a==="--no-notebook")noNotebook=true;else if(a==="--sections")sections=parse(process.argv[++i]||"");else if(a.startsWith("--sections="))sections=parse(a.slice(11));else throw new Error(`Unknown argument: ${a}`)}
function parse(v){const p=v.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);if(!p.length||p.some(x=>!allowed.includes(x)))throw new Error(`Sections must be ${allowed.join(",")}`);return p}
function sleep(ms){Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,ms)}
function last(v){return String(v).split(/\r?\n/).map(x=>x.trim()).filter(Boolean).at(-1)||""}
function esc(v){return String(v).replace(/\\/g,"\\\\").replace(/'/g,"\\'")}
function rcon(instance,command){return execFileSync("docker",["exec",controller,"npx","clusterioctl","--log-level","error","instance","send-rcon",instance,command,"--config",config],{encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim()}
function lua(instance,body){const w=`local ok,result=pcall(function() ${body} end); if ok then rcon.print(helpers.table_to_json(result)) else rcon.print(helpers.table_to_json({success=false,error=tostring(result)})) end`;return JSON.parse(last(rcon(instance,`/sc ${w}`)))}
function destinationId(){const o=execFileSync("docker",["exec",controller,"sh","-c",`npx clusterioctl --config ${config} instance list 2>/dev/null`],{encoding:"utf8"});for(const l of o.split(/\r?\n/)){const m=l.match(/^\s*clusterio-host-2-instance-1\s*\|\s*(\d+)/);if(m)return Number(m[1])}throw new Error("destination id missing")}

const helper=String.raw`
storage.inserter_lab=storage.inserter_lab or {records={}}
__inserter_b={}
function __inserter_b.make(name,entity_force_name)
	local platform_force=game.forces.player; local entity_force=game.forces[entity_force_name]; local p=platform_force.create_space_platform({name=name,planet='nauvis',starter_pack='space-platform-starter-pack'}); p.apply_starter_pack(); p.paused=false; platform_force.set_surface_hidden(p.surface,false)
	p.schedule={current=1,records={{station='nauvis'}}}
	local ox,oy=100+p.index*50,100; local tiles={}; for x=-8,8 do for y=-8,8 do tiles[#tiles+1]={name='space-platform-foundation',position={ox+x,oy+y}} end end; p.surface.set_tiles(tiles,true,false,true,false)
	local ins=p.surface.create_entity({name='bulk-inserter',position={ox,oy},direction=defines.direction.east,force=entity_force,quality='legendary'}); ins.active=true
	local ok,err=pcall(function() ins.held_stack.set_stack({name='iron-plate',count=8,quality='normal'}) end)
	local held=ins.held_stack.valid_for_read and ins.held_stack.count or 0
	storage.inserter_lab.records[name]={entity_force=entity_force_name,platform=p.index,unit=ins.unit_number}
	return {success=ok and held==8,error=ok and nil or tostring(err),name=name,index=p.index,platform_force=platform_force.name,entity_force=entity_force_name,force_bonus=entity_force.bulk_inserter_capacity_bonus,held=held,tick=game.tick,game_paused=game.tick_paused==true,platform_paused=p.paused}
end
function __inserter_b.read(name,force_name)
	local rec=storage.inserter_lab and storage.inserter_lab.records[name]; local f=game.forces[force_name or (rec and rec.entity_force)]; local p=nil
	for _,v in pairs(game.forces.player.platforms) do if v.valid and v.name==name then p=v;break end end
	if not p then return {success=false,name=name,tick=game.tick,error='platform missing',force_bonus=f and f.bulk_inserter_capacity_bonus or nil} end
	local ins=p.surface.find_entities_filtered({name='bulk-inserter'})[1]; local held=ins and ins.valid and ins.held_stack.valid_for_read and ins.held_stack.count or 0
	local phys=0; for _,e in pairs(p.surface.find_entities_filtered({})) do phys=phys+e.get_item_count('iron-plate') end
	return {success=true,name=name,tick=game.tick,game_paused=game.tick_paused==true,platform_paused=p.paused,platform_force=p.force.name,entity_force=ins and ins.force.name or nil,force_bonus=f.bulk_inserter_capacity_bonus,held=held,physical_iron_plate=phys,active=ins and ins.active or nil}
end
return {success=true,tick=game.tick,force_count=#game.forces}
`;
function install(){return{source:lua(source,helper),destination:lua(destination,helper)}}
function waitPlatform(instance,name,timeout=180000){const end=Date.now()+timeout;while(Date.now()<end){const v=lua(instance,`local p=nil;for _,x in pairs(game.forces.player.platforms) do if x.valid and x.name=='${esc(name)}' then p=x;break end end;return {success=true,index=p and p.index or nil}`);if(v.index)return v.index;sleep(1000)}throw new Error(`platform ${name} did not arrive`)}
function read(instance,name,forceName){return lua(instance,`return __inserter_b.read('${esc(name)}','${esc(forceName)}')`)}
function startTransfer(name,index){const id=destinationId();return lua(source,`local id,err=remote.call('surface_export','export_platform',${index},'player',${id});return {success=id~=nil,job_id=id,error=err,tick=game.tick}`)}

function transferCase(kind){
	const name=`${prefix}${kind}-${Date.now()}`, forceName=kind==="control"?"player":`${prefix}force-${Date.now()}`;
	let forceSetup=null;
	if(kind!=="control") forceSetup={source:lua(source,`local f=game.forces['${esc(forceName)}'] or game.create_force('${esc(forceName)}');f.bulk_inserter_capacity_bonus=11;return {success=true,name=f.name,bonus=f.bulk_inserter_capacity_bonus,force_count=#game.forces}`),destination:lua(destination,`local f=game.forces['${esc(forceName)}'] or game.create_force('${esc(forceName)}');f.bulk_inserter_capacity_bonus=0;return {success=true,name=f.name,bonus=f.bulk_inserter_capacity_bonus,force_count=#game.forces}`)};
	const setup=lua(source,`return __inserter_b.make('${esc(name)}','${esc(forceName)}')`);if(!setup.success)throw new Error(`held-item fixture failed: ${JSON.stringify(setup)}`);
	const sourcePhysical=read(source,name,forceName);const transfer=startTransfer(name,setup.index);if(!transfer.success)throw new Error(`transfer queue failed: ${JSON.stringify(transfer)}`);
	waitPlatform(destination,name);sleep(1500);const destPhysical=read(destination,name,forceName);
	if(destPhysical.held!==8||destPhysical.physical_iron_plate!==8)throw new Error(`B1-B3 STOP: real held-item shortfall: ${JSON.stringify({sourcePhysical,destPhysical})}`);
	return{success:true,kind,prediction:"full hand of 8 physically survives; adversarial destination bonus is raised before restore",force_setup:forceSetup,setup,source_physical:sourcePhysical,transfer,destination_physical:destPhysical,
		force_sync_confirmed:kind==="control"?null:destPhysical.force_bonus>=11,full_hand_confirmed:destPhysical.held===8,physical_total_confirmed:destPhysical.physical_iron_plate===8};
}

function runB4(){const name=`${prefix}b4-${Date.now()}`,forceName=`${prefix}force-${Date.now()}`;const setup=lua(source,`
	local f=game.create_force('${esc(forceName)}');f.bulk_inserter_capacity_bonus=11;local s=game.create_surface('${esc(name)}',{width=64,height=64});local ins=s.create_entity({name='bulk-inserter',position={0,0},force=f,quality='legendary'});ins.active=false;ins.active=true;ins.held_stack.set_stack({name='iron-plate',count=8,quality='normal'});ins.active=false;storage.inserter_lab.records['${esc(name)}']={force=f.name,surface=s.index};local function rd(label)local ground=0;for _,e in pairs(s.find_entities_filtered({type='item-entity'}))do ground=ground+e.get_item_count('iron-plate')end;return{label=label,tick=game.tick,game_paused=game.tick_paused==true,platform_paused=nil,bonus=f.bulk_inserter_capacity_bonus,held=ins.held_stack.valid_for_read and ins.held_stack.count or 0,ground=ground,total=(ins.held_stack.valid_for_read and ins.held_stack.count or 0)+ground}end;return{success=true,name='${esc(name)}',force=f.name,before=rd('bonus 11 seated')}
	`);if(setup.before.held!==8)throw new Error(`B4 seating control failed: ${JSON.stringify(setup)}`);
	const lowered=lua(source,`local r=storage.inserter_lab.records['${esc(name)}'];local f=game.forces[r.force];local s=game.surfaces[r.surface];local ins=s.find_entities_filtered({name='bulk-inserter'})[1];f.bulk_inserter_capacity_bonus=0;local ground=0;for _,e in pairs(s.find_entities_filtered({type='item-entity'}))do ground=ground+e.get_item_count('iron-plate')end;return{success=true,tick=game.tick,game_paused=game.tick_paused==true,platform_paused=nil,bonus=f.bulk_inserter_capacity_bonus,held=ins.held_stack.valid_for_read and ins.held_stack.count or 0,ground=ground,total=(ins.held_stack.valid_for_read and ins.held_stack.count or 0)+ground}`);
	sleep(1200);const plus60=lua(source,`local r=storage.inserter_lab.records['${esc(name)}'];local f=game.forces[r.force];local s=game.surfaces[r.surface];local ins=s.find_entities_filtered({name='bulk-inserter'})[1];local ground=0;for _,e in pairs(s.find_entities_filtered({type='item-entity'}))do ground=ground+e.get_item_count('iron-plate')end;return{success=true,tick=game.tick,game_paused=game.tick_paused==true,platform_paused=nil,bonus=f.bulk_inserter_capacity_bonus,held=ins.held_stack.valid_for_read and ins.held_stack.count or 0,ground=ground,total=(ins.held_stack.valid_for_read and ins.held_stack.count or 0)+ground}`);
	const reset=lua(source,`local r=storage.inserter_lab.records['${esc(name)}'];local f=game.forces[r.force];local s=game.surfaces[r.surface];local ins=s.find_entities_filtered({name='bulk-inserter'})[1];f.reset_technology_effects();local ground=0;for _,e in pairs(s.find_entities_filtered({type='item-entity'}))do ground=ground+e.get_item_count('iron-plate')end;return{success=true,tick=game.tick,game_paused=game.tick_paused==true,platform_paused=nil,bonus=f.bulk_inserter_capacity_bonus,held=ins.held_stack.valid_for_read and ins.held_stack.count or 0,ground=ground,total=(ins.held_stack.valid_for_read and ins.held_stack.count or 0)+ground}`);
	sleep(1200);const afterReset=lua(source,`local r=storage.inserter_lab.records['${esc(name)}'];local f=game.forces[r.force];local s=game.surfaces[r.surface];local ins=s.find_entities_filtered({name='bulk-inserter'})[1];local ground=0;for _,e in pairs(s.find_entities_filtered({type='item-entity'}))do ground=ground+e.get_item_count('iron-plate')end;return{success=true,tick=game.tick,game_paused=game.tick_paused==true,platform_paused=nil,bonus=f.bulk_inserter_capacity_bonus,held=ins.held_stack.valid_for_read and ins.held_stack.count or 0,ground=ground,total=(ins.held_stack.valid_for_read and ins.held_stack.count or 0)+ground}`);
	const readingsOk=[lowered,plus60,reset,afterReset].every(v=>v.success);return{success:readingsOk,prediction:"OPEN: measurement decides whether seated over-capacity hands survive or eject",setup,lowered,after_lower_elapsed:plus60,reset_technology_effects:reset,after_reset_elapsed:afterReset,verdict:readingsOk?(afterReset.held===8?"seated hand survives bonus drop":"held items eject or clamp after bonus drop"):"instrument failure"};}

function cleanupInstance(instance){return lua(instance,`local deleted,exports,records={},{},{};for _,s in pairs(game.surfaces)do local p=s.platform;if string.find(s.name,'${prefix}',1,true)==1 or(p and p.valid and string.find(p.name,'${prefix}',1,true)==1)then deleted[#deleted+1]=s.name;game.delete_surface(s)end end;for id,record in pairs(storage.platform_exports or{})do if record and record.platform_name and string.find(record.platform_name,'${prefix}',1,true)==1 then storage.platform_exports[id]=nil;exports[#exports+1]=id end end;for index,record in pairs(storage.locked_platforms or{})do if record and record.platform_name and string.find(record.platform_name,'${prefix}',1,true)==1 then storage.locked_platforms[index]=nil;records[#records+1]='lock:'..tostring(index) end end;for index,record in pairs(storage.destination_holds or{})do if record and record.platform_name and string.find(record.platform_name,'${prefix}',1,true)==1 then storage.destination_holds[index]=nil;records[#records+1]='hold:'..tostring(index) end end;for id,record in pairs(storage.committed_source_transfer_tombstones or{})do if record and record.platform_name and string.find(record.platform_name,'${prefix}',1,true)==1 then storage.committed_source_transfer_tombstones[id]=nil;records[#records+1]='tombstone:'..tostring(id) end end;for name,f in pairs(game.forces)do if string.find(name,'${prefix}force-',1,true)==1 then game.merge_forces(f,game.forces.player)end end;storage.inserter_lab=nil;__inserter_b=nil;game.tick_paused=false;return{success=true,deleted=deleted,exports=exports,records=records,tick=game.tick,force_count=#game.forces}`)}
function zero(instance){return lua(instance,`local function count(t)local n=0 for _,_ in pairs(t or{})do n=n+1 end return n end;local surfaces,forces,exports={},{},{};for _,s in pairs(game.surfaces)do local p=s.platform;if string.find(s.name,'${prefix}',1,true)==1 or(p and p.valid and string.find(p.name,'${prefix}',1,true)==1)then surfaces[#surfaces+1]=s.name end end;for n,_ in pairs(game.forces)do if string.find(n,'${prefix}force-',1,true)==1 then forces[#forces+1]=n end end;for id,r in pairs(storage.platform_exports or{})do local n=r and r.platform_name;if type(n)=='string'and string.find(n,'${prefix}',1,true)==1 then exports[#exports+1]=id end end;return{success=true,tick=game.tick,zero_surfaces=#surfaces==0,surfaces=surfaces,zero_storage=storage.inserter_lab==nil,game_paused=game.tick_paused==true,destination_holds=count(storage.destination_holds),locked_platforms=count(storage.locked_platforms),committed_source_transfer_tombstones=count(storage.committed_source_transfer_tombstones),lab_platform_exports=#exports,lab_forces=#forces,forces=forces,force_count=#game.forces}`)}
function ok(v,baseline){return v.zero_surfaces&&v.zero_storage&&!v.game_paused&&v.destination_holds===0&&v.locked_platforms===0&&v.committed_source_transfer_tombstones===0&&v.lab_platform_exports===0&&v.lab_forces===0&&v.force_count===baseline}
let baseline=null;function nonLabForceCount(instance){return lua(instance,`local n=0;for name,_ in pairs(game.forces)do if string.find(name,'${prefix}force-',1,true)~=1 then n=n+1 end end;return {count=n}`).count}function cleanupAll(){if(!baseline)baseline={source:nonLabForceCount(source),destination:nonLabForceCount(destination)};const cleanup={source:cleanupInstance(source),destination:cleanupInstance(destination)};sleep(500);const z={source:zero(source),destination:zero(destination)};return{baseline,cleanup,zero:z,ok:ok(z.source,baseline.source)&&ok(z.destination,baseline.destination)}}

function main(){const results={script:"tests/inserter-lab/run-b1-b4.mjs",started:new Date().toISOString(),sections,predictions:{b1:"researched-force control preserves held 8",b2:"Phase-0 raises bonus-0 destination entity force",b3:"pre-gate top-up leaves no physical residual",b4:"OPEN"},rungs:{},errors:[]};try{results.initial_reset=cleanupAll();if(!results.initial_reset.ok)throw new Error(`initial cleanup failed ${JSON.stringify(results.initial_reset)}`);results.install=install();if(sections.includes("b1")){const control=transferCase("control");results.rungs.b1={success:true,control}}if(sections.includes("b2")||sections.includes("b3")){const adversarial=transferCase("adversarial");if(sections.includes("b2"))results.rungs.b2={success:adversarial.force_sync_confirmed,adversarial};if(sections.includes("b3"))results.rungs.b3={success:adversarial.full_hand_confirmed&&adversarial.physical_total_confirmed,adversarial}}if(sections.includes("b4"))results.rungs.b4=runB4();for(const[k,v]of Object.entries(results.rungs))if(!v.success)throw new Error(`${k} failed ${JSON.stringify(v)}`)}catch(e){results.errors.push(e.stack||e.message)}finally{try{results.final_reset=cleanupAll()}catch(e){results.errors.push(`cleanup failed ${e.stack||e.message}`)}results.finished=new Date().toISOString();if(!noNotebook&&!resetOnly)appendFileSync(notebook,`\n\n## ${results.finished} - B1-B4 inserter lab\n\nPredictions: B1 held 8; B2 force sync raises bonus; B3 no residual; B4 open.\n\n\`\`\`json\n${JSON.stringify(results,null,2)}\n\`\`\`\n`);console.log(JSON.stringify(results,null,2));if(results.errors.length||!results.final_reset?.ok)process.exitCode=1}}
if(resetOnly){const r=cleanupAll();console.log(JSON.stringify(r,null,2));if(!r.ok)process.exitCode=1}else main();
