#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { appendFileSync } from "node:fs";

const controller="surface-export-controller",config="/clusterio/tokens/config-control.json",source="clusterio-host-1-instance-1",destination="clusterio-host-2-instance-1",destinationId=1351385547,prefix="fluid-lab-t1c-",notebook="tests/fluid-lab/NOTEBOOK.md";
const allowed=["r0","r1","r2"];let sections=[...allowed],resetOnly=false,noNotebook=false;
for(let i=2;i<process.argv.length;i++){const a=process.argv[i];if(a==="--reset")resetOnly=true;else if(a==="--no-notebook")noNotebook=true;else if(a==="--sections")sections=(process.argv[++i]||"").split(",");else if(a.startsWith("--sections="))sections=a.slice(11).split(",");else throw new Error(`unknown ${a}`);}if(sections.some(s=>!allowed.includes(s)))throw new Error(`sections must be ${allowed}`);
function sleep(ms){Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,ms);}function lastLine(v){return String(v).split(/\r?\n/).map(x=>x.trim()).filter(Boolean).at(-1)||"";}
function rcon(instance,command){return execFileSync("docker",["exec",controller,"npx","clusterioctl","--config",config,"--log-level","error","instance","send-rcon",instance,command],{encoding:"utf8",timeout:180000}).trim();}
function lua(instance,body){const w=`local ok,result=pcall(function() ${body} end);if ok then rcon.print(helpers.table_to_json(result))else rcon.print(helpers.table_to_json({success=false,error=tostring(result)}))end`;return JSON.parse(lastLine(rcon(instance,`/sc ${w}`)));}
function find(name,instance){return lua(instance,`for _,p in pairs(game.forces.player.platforms)do if p.valid and p.name=='${name}'then return {success=true,index=p.index,tick=game.tick}end end;return {success=true,index=nil,tick=game.tick}`);}
function waitFor(fn,timeout,label){const end=Date.now()+timeout;while(Date.now()<end){const v=fn();if(v)return v;sleep(250);}throw new Error(`timeout ${label}`);}
function clone(name){const b=find("test",source);lua(source,`local r=remote.call('surface_export','clone_platform',${b.index},'${name}');return {success=r and r.success~=false}`);return waitFor(()=>{const p=find(name,source);return p.index?p:null;},120000,`clone ${name}`);}
function cleanup(instance){return lua(instance,`for _,s in pairs(game.surfaces)do local p=s.platform;if string.find(s.name,'${prefix}',1,true)==1or(p and p.valid and string.find(p.name,'${prefix}',1,true)==1)then game.delete_surface(s)end end;local c=storage.surface_export_config or{};c.test_force_validation_failure=nil;c.preserve_failed_destination=nil;storage.fluid_lab=nil;game.tick_paused=false;return {success=true}`);}
function zero(instance){return lua(instance,`local function n(t)local c=0 for _ in pairs(t or{})do c=c+1 end return c end;local s=0;for _,x in pairs(game.surfaces)do local p=x.platform;if string.find(x.name,'${prefix}',1,true)==1or(p and p.valid and string.find(p.name,'${prefix}',1,true)==1)then s=s+1 end end;return {success=true,surfaces=s,storage=storage.fluid_lab~=nil,game_paused=game.tick_paused==true,holds=n(storage.destination_holds),locks=n(storage.locked_platforms),jobs=n(storage.async_jobs),tombstones=n(storage.committed_source_transfer_tombstones)}`);}
function cleanAll(){cleanup(source);cleanup(destination);sleep(300);const z={source:zero(source),destination:zero(destination)};z.ok=[z.source,z.destination].every(v=>v.surfaces===0&&!v.storage&&!v.game_paused&&v.holds===0&&v.locks===0&&v.jobs===0&&v.tombstones===0);return z;}
function runR0(){const name=`${prefix}r0-${Date.now()}`;return lua(source,`local s=game.create_surface('${name}',{width=64,height=64});local e=s.create_entity{name='pipe',position={0,0},force=game.forces.player};local rows={};for _,want in ipairs{1000000,1234567,1252651,2000000,5000000}do e.clear_fluid_inside();e.fluidbox[1]={name='fusion-plasma',amount=100,temperature=want};local f=e.fluidbox[1];rows[#rows+1]={tick=game.tick,written=want,read=f and f.temperature or nil,error=f and f.temperature-want or nil,amount=f and f.amount or nil}end;return {success=true,prediction='same-tick float precision error grows with magnitude',rows=rows}`);}
function readFixture(name,instance,positions,label){return lua(instance,`local p=nil;for _,v in pairs(game.forces.player.platforms)do if v.name=='${name}'then p=v end end;local function one(pos)local e=p.surface.find_entity('pipe',pos);if not e then return {missing=true}end;local f=e.fluidbox[1];local ok_id,id=pcall(function()return e.fluidbox.get_fluid_segment_id(1)end);local ok_c,c=pcall(function()return e.fluidbox.get_fluid_segment_contents(1)end);return {entity=e.name,tick=game.tick,direct=f and{name=f.name,amount=f.amount,temp=f.temperature,energy=f.amount*f.temperature}or nil,segment_id=ok_id and id or nil,segment=ok_c and c or nil}end;return {success=true,label='${label}',tick=game.tick,isolated=one{x=${positions.isolated.x},y=${positions.isolated.y}},plumbed=one{x=${positions.plumbed.x},y=${positions.plumbed.y}}}`);}
function buildFixtures(name){return lua(source,`local p=nil;for _,v in pairs(game.forces.player.platforms)do if v.name=='${name}'then p=v end end;local iso=nil;for _,t in pairs(p.surface.find_tiles_filtered{name='space-platform-foundation'})do local clear=true;for _,e in pairs(p.surface.find_entities_filtered{position=t.position,radius=4})do if e.fluidbox and #e.fluidbox>0 then clear=false;break end end;if clear and p.surface.can_place_entity{name='pipe',position=t.position,force=p.force}then iso=p.surface.create_entity{name='pipe',position=t.position,force=p.force};break end end;if not iso then error('no isolated pipe site')end;iso.fluidbox[1]={name='fusion-plasma',amount=100,temperature=1234567};local near=0;for _,e in pairs(p.surface.find_entities_filtered{position=iso.position,radius=4})do if e~=iso and e.fluidbox and #e.fluidbox>0 then near=near+1 end end;if near~=0 then error('isolation assertion failed')end;local reactor=p.surface.find_entities_filtered{name='fusion-reactor'}[1];if not reactor then error('reactor missing')end;local conns=reactor.fluidbox.get_pipe_connections(2);local plumb=nil;for _,c in pairs(conns or{})do local pos=c.target_position or c.position;if pos and p.surface.can_place_entity{name='pipe',position=pos,force=p.force}then plumb=p.surface.create_entity{name='pipe',position=pos,force=p.force};break end end;if not plumb then error('no plumbable reactor output')end;local f=plumb.fluidbox[1];return {success=true,tick=game.tick,isolated={x=iso.position.x,y=iso.position.y,nearby_fluidboxes=near,read={amount=iso.fluidbox[1].amount,temp=iso.fluidbox[1].temperature}},plumbed={x=plumb.position.x,y=plumb.position.y,read=f and{amount=f.amount,temp=f.temperature}or nil},reactor_output_segment=reactor.fluidbox.get_fluid_segment_id(2),plumbed_segment=plumb.fluidbox.get_fluid_segment_id(1)}`);}
function runR1(){const name=`${prefix}r1-${Date.now()}`,p=clone(name),fixture=buildFixtures(name),positions={isolated:fixture.isolated,plumbed:fixture.plumbed};lua(source,`local p=nil;for _,v in pairs(game.forces.player.platforms)do if v.name=='${name}'then p=v end end;p.paused=true;return {success=true,tick=game.tick}`);const before=readFixture(name,source,positions,"source frozen");lua(destination,`remote.call('surface_export','configure',{debug_mode=true,test_force_validation_failure=true,preserve_failed_destination=true});return {success=true}`);rcon(source,`/transfer-platform ${p.index} ${destinationId}`);waitFor(()=>{const d=find(name,destination);if(!d.index)return null;const q=lua(destination,`return {success=true,jobs=table_size(storage.async_jobs or{}),preserve=(storage.surface_export_config or{}).preserve_failed_destination}`);return q.jobs===0&&q.preserve!==true?d:null;},180000,"frozen preserved import");const after=readFixture(name,destination,positions,"destination frozen");const b=before.isolated.direct,a=after.isolated.direct;const isolated={source:b,destination:a,volume_delta:a.amount-b.amount,energy_delta:a.energy-b.energy};const success=Math.abs(isolated.volume_delta)<=1e-6&&Math.abs(isolated.energy_delta)<=1e-6;if(!success)throw new Error(`R1(a) HARD STOP ${JSON.stringify(isolated)}`);return{success,prediction:'isolated ownership stable; plumbed shares reactor segment',fixture,before,after,isolated,plumbed_same_segment_source:fixture.reactor_output_segment===fixture.plumbed_segment};}
function runR2(r0){const source={volume:600,energy:742548600},destination={volume:600,energy:743230396.25};const nearest=t=>r0.rows.reduce((best,row)=>Math.abs(row.written-t)<Math.abs(best.written-t)?row:best,r0.rows[0]);const q=nearest(1252651);const expectedAdjustment=(q.read-q.written)*100;const raw=destination.energy-source.energy;return{success:true,prediction:'quantization explains the prior residual or residual remains UNEXPLAINED',raw_delta:raw,quantization_adjustment:expectedAdjustment,residual:raw-expectedAdjustment,classification:Math.abs(raw-expectedAdjustment)<=1?'quantization':'UNEXPLAINED'};}
function main(){const out={script:"tests/fluid-lab/run-t1c.mjs",started:new Date().toISOString(),sections,predictions:{r0:'same-tick precision sweep',r1:'isolated stable; plumbed segment mechanics',r2:'recompute prior residual'},rungs:{},errors:[]};try{out.initial_reset=cleanAll();if(!out.initial_reset.ok)throw new Error('initial cleanup failed');if(sections.includes('r0'))out.rungs.r0=runR0();if(sections.includes('r1'))out.rungs.r1=runR1();if(sections.includes('r2'))out.rungs.r2=runR2(out.rungs.r0||runR0());}catch(e){out.errors.push(e.stack||e.message);}finally{out.final_reset=cleanAll();out.finished=new Date().toISOString();if(!noNotebook&&!resetOnly)appendFileSync(notebook,`\n\n## ${out.finished} - T1c plasma decomposition\n\nPredictions stated before execution: R0 precision sweep; R1 isolated ownership stable and plumbed engine mechanics; R2 honest residual classification.\n\n\`\`\`json\n${JSON.stringify(out,null,2)}\n\`\`\`\n`);console.log(JSON.stringify(out,null,2));if(out.errors.length||!out.final_reset.ok)process.exitCode=1;}}
if(resetOnly){const r=cleanAll();console.log(JSON.stringify(r,null,2));if(!r.ok)process.exitCode=1;}else main();
