-- GENERATED by the version bump (patch-and-reset.ps1 / deploy-cluster.ps1 via
-- tools/shared/version-utils.ps1 Update-ModuleVersionStamp). Do not edit by hand — the single
-- source of truth is package.json; test/module-version-stamp.test.cjs fails the suite on drift.
--
-- WHY THIS EXISTS (SC-72): the runtime version oracle for the deploy boot checks. The old boot
-- check proved only that SOME plugin answers RCON — a plain restart reuses the old patched
-- script.dat, so stale module code passed it. remote.call('surface_export','get_module_version')
-- returns this stamp, and the boot check compares it against the version just deployed.
return "0.10.206"
