// Seed-prep: run committed CONSTRUCTION operations against a seed save in the isolated
// Factorio and emit the next candidate save. This is the scripted replacement for hand-curating
// fixtures into the seed (owner decision 2026-07-17): `prior golden source → seed-prep →
// candidate-vN → build-save.mjs bake`, fully reproducible from the repository.
//
// gallery-runtime.lua stays verify-only; all construction lives in seed-prep-ops.lua and runs
// ONLY here — never on the cluster.
//
// Usage:
//   node tests/lab-gallery/seed-prep.mjs --seed docker/seed-data/lab-saves/lab-gallery-source-surface-export-2.0.77.zip \
//     --output /path/candidate-v10.zip [--container surface-export-host-2]

import { existsSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
	docker, launchIsolatedFactorio, runtimeCall, sleep, tailFactorioLog,
	teardownIsolatedFactorio, waitForRuntime, waitForStableSave,
} from "./isolated-factorio.mjs";
import { loadGalleryManifest } from "./manifest.mjs";
// ONE template source (test-foundation.mjs) for the stamped cells; ONE card source (manifest.json).
import { LEGEND, TEMPLATE_ROWS } from "./test-foundation.mjs";

const REMOTE_ROOT = "/tmp/surface-export-lab-gallery-seed-prep";
const PORTS = { gamePort: "34976", rconPort: "27976", rconPassword: "seed-prep-only" };
// Plasma must be GENERATED by running the reactor (output writes are engine-rejected — Pitfall #21,
// fusion outputs are engine-managed), so the build polls until the shared segment holds plasma.
const PLASMA_DEADLINE_MS = 600_000; // 10 min: isolated accumulation is slower than the live build (~1.8 plasma after 2 min measured 2026-07-18)

export function parseArguments(argv) {
	const result = { seed: null, output: null, container: "surface-export-host-2" };
	for (let index = 0; index < argv.length; index += 1) {
		const argument = argv[index];
		if (argument === "--seed") result.seed = argv[++index];
		else if (argument === "--output") result.output = argv[++index];
		else if (argument === "--container") result.container = argv[++index];
		else throw new Error(`unknown argument ${argument}`);
	}
	if (!result.seed) throw new Error("--seed <save.zip> is required");
	if (!result.output) throw new Error("--output <candidate.zip> is required");
	if (!/^surface-export-host-\d+$/.test(result.container)) throw new Error(`unsupported container ${result.container}`);
	return result;
}

async function main() {
	const options = parseArguments(process.argv.slice(2));
	if (!existsSync(options.seed)) throw new Error(`seed does not exist: ${options.seed}`);
	if (existsSync(options.output)) throw new Error(`refusing to overwrite ${options.output}`);

	const opsLua = fileURLToPath(new URL("./seed-prep-ops.lua", import.meta.url));
	const driver = fileURLToPath(new URL("./runtime-driver.cjs", import.meta.url));
	const config = fileURLToPath(new URL("./seed-prep-config.ini", import.meta.url));

	const handle = launchIsolatedFactorio({
		container: options.container, remoteRoot: REMOTE_ROOT,
		seed: options.seed, config,
		files: [[driver, "runtime-driver.cjs"], [opsLua, "ops.lua"]],
		timeoutSeconds: 900,
		...PORTS,
	});
	const boundaryErrors = [];
	try {
		await waitForRuntime(handle, PORTS, { operation: "preflight" });

		// IDEMPOTENT census stage: a seed that ALREADY carries the baked census-fusion fixture (every
		// golden source since the first census bake) is VERIFIED in place — never rebuilt (the build op
		// correctly refuses a rebuild). Only a pre-census seed runs the construct/park/freeze recipe.
		let existing = null;
		try { existing = runtimeCall(handle, PORTS, { operation: "measure_census_fusion" }); }
		catch (error) { console.error(`[seed-prep] census probe on seed failed (pre-census seed assumed): ${error.message}`); }
		let censusFingerprint;
		if (existing && existing.success !== false && (existing.plasma_segment || 0) >= 5) {
			console.error(`[seed-prep] census-fusion already baked (plasma=${existing.plasma_segment}) — verified, skipping rebuild`);
			censusFingerprint = existing;
		} else {
			const built = runtimeCall(handle, PORTS, { operation: "build_census_fusion" });
			console.error(`[seed-prep] built: ${JSON.stringify(built)}`);

			// Run WITH the throttled load attached until the shared segment parks stock: the reactor
			// outpaces the small draw, fills the segment, and stalls at full_output — the live-proven
			// recipe (gallery HITL build, 2026-07-18, 2.0.77: full_output + plasma 10.00 reached with
			// the 10 MW load present; removing the load entirely stops production instead of parking).
			const parkDeadline = Date.now() + PLASMA_DEADLINE_MS;
			let reading;
			do {
				await sleep(2_000);
				reading = runtimeCall(handle, PORTS, { operation: "measure_census_fusion" });
				console.error(`[seed-prep] plasma=${reading.plasma_segment} coolant=${reading.coolant} fuel=${reading.fuel_cells} reactor=${reading.reactor_status} generators=${JSON.stringify(reading.generator_status)}`);
			} while (reading.plasma_segment < 5 && Date.now() < parkDeadline); // wait for real parked stock (steady state ~9-10), not the first trickle
			if (reading.plasma_segment < 5) throw new Error(`no plasma parked in the shared segment before the deadline: ${JSON.stringify(reading)}`);

			const fingerprint = runtimeCall(handle, PORTS, { operation: "freeze_census_fusion" });
			censusFingerprint = fingerprint;
			if (fingerprint.all_frozen !== true || fingerprint.all_indestructible !== true) {
				throw new Error(`freeze incomplete: ${JSON.stringify(fingerprint)}`);
			}
			// The law-bearing invariant: plasma present + the generator's plasma box reads a nil segment
			// ID (buffer-class visibility). reactor_plasma_seg_visible is asserted only when the stock
			// parked reactor-side (the isolated steady state parks it generator-side instead — measured
			// 2026-07-18, 2.0.77).
			if (fingerprint.plasma_segment <= 0 || fingerprint.generator_plasma_seg_nil !== true) {
				throw new Error(`plasma/visibility invariant not reproduced: ${JSON.stringify(fingerprint)}`);
			}
		}

		// Port two fixtures onto the EXISTING golden omnibus platform (lab-omnibus-state-v1). Each cell is
		// stamped from the shared test-foundation template, the fixture built, then physically measured
		// and gated against the manifest fingerprint (single source of truth) before the save is taken.
		const repoRoot = new URL("../../", import.meta.url);
		const manifest = loadGalleryManifest(repoRoot);
		const cardFor = id => {
			const fixture = manifest.fixtures.find(entry => entry.id === id);
			if (!fixture || !fixture.testCard) throw new Error(`manifest is missing a testCard for ${id}`);
			const card = fixture.testCard;
			return { law: card.law, action: card.action, expect: card.expected, forbidden: card.forbidden };
		};
		// PAD RELOCATION (owner directive 2026-07-18): all 13 pads live in a hub-adjacent grid
		// (columns x=8/36/64/92, rows y=-20/-6/8/22) so they are visible from the hub without the
		// editor. clear_legacy_strip first clears the migrated-out zone row's plain foundation (the
		// only-onto-empty stamp refuses foreign tiles); each relocation stamps the new pad then moves
		// the interior via clone_area. Idempotent: already_relocated / skipped pads are verified, not
		// rebuilt.
		const RELOCATIONS = [
			{ id: "omnibus-adversarial-inventory", oldX: 34, oldY: -100, newX: 8, newY: -20 },
			{ id: "omnibus-heat-temperature", oldX: 62, oldY: -100, newX: 36, newY: -20 },
			{ id: "omnibus-decider-latch", oldX: 62, oldY: -114, newX: 64, newY: -20 },
			{ id: "omnibus-midcraft-progress", oldX: 62, oldY: -128, newX: 92, newY: -20 },
			{ id: "omnibus-burner-fuel", oldX: 34, oldY: -142, newX: 8, newY: -6 },
			{ id: "omnibus-equipment-grid", oldX: 62, oldY: -142, newX: 36, newY: -6 },
			{ id: "omnibus-circuit-config", oldX: 34, oldY: -156, newX: 64, newY: -6 },
			{ id: "omnibus-module-bonus-progress", oldX: 62, oldY: -156, newX: 92, newY: -6 },
			{ id: "omnibus-crafting-fluids", oldX: 34, oldY: -170, newX: 8, newY: 8 },
			{ id: "omnibus-ghosts-and-proxies", oldX: 62, oldY: -170, newX: 36, newY: 8 },
			{ id: "omnibus-ground-items", oldX: 34, oldY: -184, newX: 64, newY: 8 },
			{ id: "inserter-held-capacity", oldX: 34, oldY: -128, newX: 92, newY: 8 },
			{ id: "no-tick-sync-frozen-pair", oldX: 34, oldY: -114, newX: 8, newY: 22 },
		];
		const strip = runtimeCall(handle, PORTS, { operation: "clear_legacy_strip" });
		console.error(`[seed-prep] legacy strip: ${JSON.stringify(strip)}`);
		const relocations = {};
		for (const pad of RELOCATIONS) {
			runtimeCall(handle, PORTS, {
				operation: "stamp_test_cell", origin_x: pad.newX, origin_y: pad.newY,
				name: pad.id, rows: TEMPLATE_ROWS, legend: LEGEND, card: cardFor(pad.id),
			});
			const moved = runtimeCall(handle, PORTS, {
				operation: "relocate_pad", name: pad.id,
				old_origin_x: pad.oldX, old_origin_y: pad.oldY,
				new_origin_x: pad.newX, new_origin_y: pad.newY,
			});
			if (moved.success === false) throw new Error(`${pad.id} relocation failed: ${moved.error}`);
			relocations[pad.id] = moved;
			console.error(`[seed-prep] relocated ${pad.id}: ${JSON.stringify(moved)}`);
		}

		const cells = [
			{ id: "inserter-held-capacity", originX: 92, originY: 8, build: "build_inserter_held", measure: "measure_inserter_held" },
			{ id: "no-tick-sync-frozen-pair", originX: 8, originY: 22, build: "build_no_tick_pair", measure: "measure_no_tick_pair" },
			{ id: "repin-beacon-speed", originX: 36, originY: 22, build: "build_repin_beacon", measure: "measure_repin_beacon" },
		];
		const portedFixtures = {};
		for (const cell of cells) {
			runtimeCall(handle, PORTS, {
				operation: "stamp_test_cell", origin_x: cell.originX, origin_y: cell.originY,
				name: cell.id, rows: TEMPLATE_ROWS, legend: LEGEND, card: cardFor(cell.id),
			});
			// Build/measure positions come from the manifest anchors (single source shared with
			// both meters) — the ops fail loud without them.
			const fixtureEntry = manifest.fixtures.find(entry => entry.id === cell.id);
			const anchors = Object.fromEntries((fixtureEntry.anchors || [])
				.map(a => [a.entity, { x: a.x, y: a.y }]));
			const built = runtimeCall(handle, PORTS, { operation: cell.build, anchors });
			const measured = runtimeCall(handle, PORTS, { operation: cell.measure, anchors });
			portedFixtures[cell.id] = measured;
			console.error(`[seed-prep] ported ${cell.id}: built=${JSON.stringify(built)} measured=${JSON.stringify(measured)}`);
		}
		// Verdict: every measured fingerprint field matches the manifest. crafting-progress absorbs a
		// save/load ULP (1e-9); forceBulkBonus is raise-only so accept any actual at or above the floor.
		for (const cell of cells) {
			const fixture = manifest.fixtures.find(entry => entry.id === cell.id);
			const measured = portedFixtures[cell.id];
			for (const [key, expected] of Object.entries(fixture.fingerprint)) {
				const actual = measured[key];
				if (key === "forceBulkBonus" && typeof actual === "number" && typeof expected === "number" && actual >= expected) continue;
				const ok = key === "progress" && typeof actual === "number" && typeof expected === "number"
					? Math.abs(actual - expected) <= 1e-9 : actual === expected;
				if (!ok) throw new Error(`${cell.id}.${key} measured ${JSON.stringify(actual)}, expected ${JSON.stringify(expected)}`);
			}
		}

		// HISTORICAL: the zone->pad MIGRATIONS stage (migrate_omnibus_zone, 2026-07-18) ran once
		// against the pre-pad seed and its result is baked into the committed golden source; the stage
		// was removed when the hub-adjacent relocation reused the old zone band (y=-6..6) for the new
		// y=-6 pad row, which confounds the zone rectangles' idempotency predicate. The op remains in
		// seed-prep-ops.lua; clear_legacy_strip refuses to run over an unmigrated strip.
		const migrations = { removedStage: "zones migrated + relocated; see RELOCATIONS" };

		// HOLD-BUFFER PAIRS (card 3, owner-adjudicated 2026-07-18): three live/held pairs on six
		// generation-free mini-platforms, baked PAUSED. Physical fixtures are baked; hold records
		// stay runtime staging via the production remote (the accepted deviation). Build ops are
		// idempotent and RE-SEED drifting state (spoil 0.95) on every bake.
		const HOLD_PAIRS = [
			{ id: "hold-buffer-spoil", build: "build_hold_spoil", measure: "measure_hold_spoil" },
			{ id: "hold-buffer-damage", build: "build_hold_damage", measure: "measure_hold_damage" },
			{ id: "hold-buffer-pod", build: "build_hold_pod", measure: "measure_hold_pod" },
		];
		const holdPairs = {};
		for (const pair of HOLD_PAIRS) {
			const built = runtimeCall(handle, PORTS, { operation: pair.build });
			if (built.success === false) throw new Error(`${pair.id} build failed: ${built.error}`);
			const measured = runtimeCall(handle, PORTS, { operation: pair.measure });
			if (measured.success === false) throw new Error(`${pair.id} measure failed: ${measured.error}`);
			holdPairs[pair.id] = measured;
			console.error(`[seed-prep] hold pair ${pair.id}: built=${JSON.stringify(built)} measured=${JSON.stringify(measured)}`);
			const fixture = manifest.fixtures.find(entry => entry.id === pair.id);
			if (!fixture) throw new Error(`manifest is missing fixture ${pair.id}`);
			for (const [key, expected] of Object.entries(fixture.fingerprint)) {
				if (measured[key] !== expected) {
					throw new Error(`${pair.id}.${key} measured ${JSON.stringify(measured[key])}, expected ${JSON.stringify(expected)}`);
				}
			}
		}

		// Walkable grid (owner request 2026-07-19): join the pads to the hub with foundation so a
		// character can physically walk the whole test floor. Idempotent (fills empty-space only).
		const walkways = runtimeCall(handle, PORTS, { operation: "fill_walkways" });
		console.error(`[seed-prep] walkways: ${JSON.stringify(walkways)}`);

		const saveName = "seed-prep-candidate";
		runtimeCall(handle, PORTS, { operation: "save", save_name: saveName });
		const remoteSave = `${REMOTE_ROOT}/saves/${saveName}.zip`;
		await waitForStableSave(options.container, remoteSave);
		docker(["cp", `${options.container}:${remoteSave}`, options.output], { timeout: 180_000 });

		console.log(JSON.stringify({ status: "PASS", candidate: options.output, fingerprint: censusFingerprint, portedFixtures, migrations, holdPairs }, null, 2));
	} catch (error) {
		try { console.error(`isolated Factorio tail:\n${tailFactorioLog(handle)}`); } catch { /* launch may have died early */ }
		throw error;
	} finally {
		await teardownIsolatedFactorio(handle, boundaryErrors);
	}
	if (boundaryErrors.length) throw new AggregateError(boundaryErrors, "seed-prep passed but the teardown boundary was not clean");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	main().catch(error => { console.error(error); process.exitCode = 1; });
}
