// Seed-prep: run committed CONSTRUCTION operations against a seed save in the isolated
// Factorio and emit the next candidate save. This is the scripted replacement for hand-curating
// fixtures into the seed (owner decision 2026-07-17): `prior golden source → seed-prep →
// candidate-vN → build-save.mjs bake`, fully reproducible from the repository.
//
// gallery-runtime.lua stays verify-only; all construction lives in seed-prep-ops.lua and runs
// ONLY here — never on the cluster.
//
// Usage:
//   node tests/lab-gallery/seed-prep.mjs --seed docker/seed-data/lab-saves/lab-gallery-source-surface-export-2.0.77.zip \
//     --output /path/candidate-v10.zip [--container surface-export-host-2]

import { existsSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
	docker, launchIsolatedFactorio, runtimeCall, sleep, tailFactorioLog,
	teardownIsolatedFactorio, waitForRuntime, waitForStableSave,
} from "./isolated-factorio.mjs";
import { buildFiveByFiveLoop } from "./fixture-layout.mjs";
import { loadGalleryManifest } from "./manifest.mjs";
// ONE template source (test-foundation.mjs) for the stamped cells; ONE card source (manifest.json).
import { LEGEND, TEMPLATE_ROWS } from "./test-foundation.mjs";

const REMOTE_ROOT = "/tmp/surface-export-lab-gallery-seed-prep";
const PORTS = { gamePort: "34976", rconPort: "27976", rconPassword: "seed-prep-only" };
// Plasma must be GENERATED by running the reactor (output writes are engine-rejected — Pitfall #21,
// fusion outputs are engine-managed), so the build polls until the shared segment holds plasma.
const PLASMA_DEADLINE_MS = 600_000; // 10 min: isolated accumulation is slower than the live build (~1.8 plasma after 2 min measured 2026-07-18)

export function parseArguments(argv) {
	const result = { seed: null, output: null, container: "surface-export-host-2" };
	for (let index = 0; index < argv.length; index += 1) {
		const argument = argv[index];
		if (argument === "--seed") result.seed = argv[++index];
		else if (argument === "--output") result.output = argv[++index];
		else if (argument === "--container") result.container = argv[++index];
		else throw new Error(`unknown argument ${argument}`);
	}
	if (!result.seed) throw new Error("--seed <save.zip> is required");
	if (!result.output) throw new Error("--output <candidate.zip> is required");
	if (!/^surface-export-host-\d+$/.test(result.container)) throw new Error(`unsupported container ${result.container}`);
	return result;
}

async function main() {
	const options = parseArguments(process.argv.slice(2));
	if (!existsSync(options.seed)) throw new Error(`seed does not exist: ${options.seed}`);
	if (existsSync(options.output)) throw new Error(`refusing to overwrite ${options.output}`);

	const opsLua = fileURLToPath(new URL("./seed-prep-ops.lua", import.meta.url));
	const driver = fileURLToPath(new URL("./runtime-driver.cjs", import.meta.url));
	const config = fileURLToPath(new URL("./seed-prep-config.ini", import.meta.url));
	// Ship the shared meter library as the runtime-driver prelude (FixtureMeters) so the belt pad
	// build/measure ops reuse the SAME measurement code as the bake and reload meters (single source).
	const meters = fileURLToPath(new URL("../../docker/seed-data/external_plugins/surface_export/module/utils/fixture-meters.lua", import.meta.url));

	const handle = launchIsolatedFactorio({
		container: options.container, remoteRoot: REMOTE_ROOT,
		seed: options.seed, config,
		files: [[driver, "runtime-driver.cjs"], [meters, "fixture-meters.lua"], [opsLua, "ops.lua"]],
		timeoutSeconds: 900,
		runtimeLuaName: "ops.lua", metersLuaName: "fixture-meters.lua",
		...PORTS,
	});
	const boundaryErrors = [];
	try {
		await waitForRuntime(handle, PORTS, { operation: "preflight" });

		// IDEMPOTENT census stage: a seed that ALREADY carries the baked census-fusion fixture (every
		// golden source since the first census bake) is VERIFIED in place — never rebuilt (the build op
		// correctly refuses a rebuild). Only a pre-census seed runs the construct/park/freeze recipe.
		let existing = null;
		try { existing = runtimeCall(handle, PORTS, { operation: "measure_census_fusion" }); }
		catch (error) { console.error(`[seed-prep] census probe on seed failed (pre-census seed assumed): ${error.message}`); }
		let censusFingerprint;
		if (existing && existing.success !== false && (existing.plasma_segment || 0) >= 5) {
			console.error(`[seed-prep] census-fusion already baked (plasma=${existing.plasma_segment}) — verified, skipping rebuild`);
			censusFingerprint = existing;
		} else {
			const built = runtimeCall(handle, PORTS, { operation: "build_census_fusion" });
			console.error(`[seed-prep] built: ${JSON.stringify(built)}`);

			// Run WITH the throttled load attached until the shared segment parks stock: the reactor
			// outpaces the small draw, fills the segment, and stalls at full_output — the live-proven
			// recipe (gallery HITL build, 2026-07-18, 2.0.77: full_output + plasma 10.00 reached with
			// the 10 MW load present; removing the load entirely stops production instead of parking).
			const parkDeadline = Date.now() + PLASMA_DEADLINE_MS;
			let reading;
			do {
				await sleep(2_000);
				reading = runtimeCall(handle, PORTS, { operation: "measure_census_fusion" });
				console.error(`[seed-prep] plasma=${reading.plasma_segment} coolant=${reading.coolant} fuel=${reading.fuel_cells} reactor=${reading.reactor_status} generators=${JSON.stringify(reading.generator_status)}`);
			} while (reading.plasma_segment < 5 && Date.now() < parkDeadline); // wait for real parked stock (steady state ~9-10), not the first trickle
			if (reading.plasma_segment < 5) throw new Error(`no plasma parked in the shared segment before the deadline: ${JSON.stringify(reading)}`);

			const fingerprint = runtimeCall(handle, PORTS, { operation: "freeze_census_fusion" });
			censusFingerprint = fingerprint;
			if (fingerprint.all_frozen !== true || fingerprint.all_indestructible !== true) {
				throw new Error(`freeze incomplete: ${JSON.stringify(fingerprint)}`);
			}
			// The law-bearing invariant: plasma present + the generator's plasma box reads a nil segment
			// ID (buffer-class visibility). reactor_plasma_seg_visible is asserted only when the stock
			// parked reactor-side (the isolated steady state parks it generator-side instead — measured
			// 2026-07-18, 2.0.77).
			if (fingerprint.plasma_segment <= 0 || fingerprint.generator_plasma_seg_nil !== true) {
				throw new Error(`plasma/visibility invariant not reproduced: ${JSON.stringify(fingerprint)}`);
			}
		}

		// Port two fixtures onto the EXISTING golden omnibus platform (lab-omnibus-state-v1). Each cell is
		// stamped from the shared test-foundation template, the fixture built, then physically measured
		// and gated against the manifest fingerprint (single source of truth) before the save is taken.
		const repoRoot = new URL("../../", import.meta.url);
		const manifest = loadGalleryManifest(repoRoot);
		const cardFor = id => {
			const fixture = manifest.fixtures.find(entry => entry.id === id);
			if (!fixture || !fixture.testCard) throw new Error(`manifest is missing a testCard for ${id}`);
			const card = fixture.testCard;
			return { law: card.law, action: card.action, expect: card.expected, forbidden: card.forbidden };
		};
		// Pad grid origins are read from the manifest (v3 `origin` field) — the single source of truth.
		// The hardcoded newX/newY / originX/originY literals were retired here (they now live only in the
		// manifest); the historical relocation SOURCE coords (oldX/oldY) are migration history, not origins.
		const originOf = id => {
			const fixture = manifest.fixtures.find(entry => entry.id === id);
			if (!fixture || !fixture.origin) throw new Error(`manifest fixture ${id} has no pad origin`);
			return fixture.origin;
		};
		const anchorsFor = id => Object.fromEntries(
			((manifest.fixtures.find(entry => entry.id === id) || {}).anchors || []).map(a => [a.entity, { x: a.x, y: a.y }]));
		// PAD RELOCATION (owner directive 2026-07-18): all 13 pads live in a hub-adjacent grid
		// (columns x=8/36/64/92, rows y=-20/-6/8/22) so they are visible from the hub without the
		// editor. clear_legacy_strip first clears the migrated-out zone row's plain foundation (the
		// only-onto-empty stamp refuses foreign tiles); each relocation stamps the new pad then moves
		// the interior via clone_area. Idempotent: already_relocated / skipped pads are verified, not
		// rebuilt.
		const RELOCATIONS = [
			{ id: "omnibus-adversarial-inventory", oldX: 34, oldY: -100 },
			{ id: "omnibus-heat-temperature", oldX: 62, oldY: -100 },
			{ id: "omnibus-decider-latch", oldX: 62, oldY: -114 },
			{ id: "omnibus-midcraft-progress", oldX: 62, oldY: -128 },
			{ id: "omnibus-burner-fuel", oldX: 34, oldY: -142 },
			{ id: "omnibus-equipment-grid", oldX: 62, oldY: -142 },
			{ id: "omnibus-circuit-config", oldX: 34, oldY: -156 },
			{ id: "omnibus-module-bonus-progress", oldX: 62, oldY: -156 },
			{ id: "omnibus-crafting-fluids", oldX: 34, oldY: -170 },
			{ id: "omnibus-ghosts-and-proxies", oldX: 62, oldY: -170 },
			{ id: "omnibus-ground-items", oldX: 34, oldY: -184 },
			{ id: "inserter-held-capacity", oldX: 34, oldY: -128 },
			{ id: "no-tick-sync-frozen-pair", oldX: 34, oldY: -114 },
		];
		const strip = runtimeCall(handle, PORTS, { operation: "clear_legacy_strip" });
		console.error(`[seed-prep] legacy strip: ${JSON.stringify(strip)}`);
		const relocations = {};
		for (const pad of RELOCATIONS) {
			const origin = originOf(pad.id);
			runtimeCall(handle, PORTS, {
				operation: "stamp_test_cell", origin_x: origin.x, origin_y: origin.y,
				name: pad.id, rows: TEMPLATE_ROWS, legend: LEGEND, card: cardFor(pad.id),
			});
			const moved = runtimeCall(handle, PORTS, {
				operation: "relocate_pad", name: pad.id,
				old_origin_x: pad.oldX, old_origin_y: pad.oldY,
				new_origin_x: origin.x, new_origin_y: origin.y,
			});
			if (moved.success === false) throw new Error(`${pad.id} relocation failed: ${moved.error}`);
			relocations[pad.id] = moved;
			console.error(`[seed-prep] relocated ${pad.id}: ${JSON.stringify(moved)}`);
		}

		const cells = [
			{ id: "inserter-held-capacity", build: "build_inserter_held", measure: "measure_inserter_held" },
			{ id: "no-tick-sync-frozen-pair", build: "build_no_tick_pair", measure: "measure_no_tick_pair" },
			{ id: "repin-beacon-speed", build: "build_repin_beacon", measure: "measure_repin_beacon" },
		];
		const portedFixtures = {};
		for (const cell of cells) {
			const origin = originOf(cell.id);
			runtimeCall(handle, PORTS, {
				operation: "stamp_test_cell", origin_x: origin.x, origin_y: origin.y,
				name: cell.id, rows: TEMPLATE_ROWS, legend: LEGEND, card: cardFor(cell.id),
			});
			// Build/measure positions come from the manifest anchors (single source shared with
			// both meters) — the ops fail loud without them.
			const anchors = anchorsFor(cell.id);
			const built = runtimeCall(handle, PORTS, { operation: cell.build, anchors });
			const measured = runtimeCall(handle, PORTS, { operation: cell.measure, anchors });
			portedFixtures[cell.id] = measured;
			console.error(`[seed-prep] ported ${cell.id}: built=${JSON.stringify(built)} measured=${JSON.stringify(measured)}`);
		}
		// Verdict: every measured fingerprint field matches the manifest. crafting-progress absorbs a
		// save/load ULP (1e-9); forceBulkBonus is raise-only so accept any actual at or above the floor.
		for (const cell of cells) {
			const fixture = manifest.fixtures.find(entry => entry.id === cell.id);
			const measured = portedFixtures[cell.id];
			for (const [key, expected] of Object.entries(fixture.fingerprint)) {
				const actual = measured[key];
				if (key === "forceBulkBonus" && typeof actual === "number" && typeof expected === "number" && actual >= expected) continue;
				const ok = key === "progress" && typeof actual === "number" && typeof expected === "number"
					? Math.abs(actual - expected) <= 1e-9 : actual === expected;
				if (!ok) throw new Error(`${cell.id}.${key} measured ${JSON.stringify(actual)}, expected ${JSON.stringify(expected)}`);
			}
		}

		// HISTORICAL: the zone->pad MIGRATIONS stage (migrate_omnibus_zone, 2026-07-18) ran once
		// against the pre-pad seed and its result is baked into the committed golden source; the stage
		// was removed when the hub-adjacent relocation reused the old zone band (y=-6..6) for the new
		// y=-6 pad row, which confounds the zone rectangles' idempotency predicate. The op remains in
		// seed-prep-ops.lua; clear_legacy_strip refuses to run over an unmigrated strip.
		const migrations = { removedStage: "zones migrated + relocated; see RELOCATIONS" };

		// HOLD-BUFFER PAIRS (card 3, owner-adjudicated 2026-07-18): three live/held pairs on six
		// generation-free mini-platforms, baked PAUSED. Physical fixtures are baked; hold records
		// stay runtime staging via the production remote (the accepted deviation). Build ops are
		// idempotent and RE-SEED drifting state (spoil 0.95) on every bake.
		const HOLD_PAIRS = [
			{ id: "hold-buffer-spoil", build: "build_hold_spoil", measure: "measure_hold_spoil" },
			{ id: "hold-buffer-damage", build: "build_hold_damage", measure: "measure_hold_damage" },
			{ id: "hold-buffer-pod", build: "build_hold_pod", measure: "measure_hold_pod" },
		];
		const holdPairs = {};
		for (const pair of HOLD_PAIRS) {
			const built = runtimeCall(handle, PORTS, { operation: pair.build });
			if (built.success === false) throw new Error(`${pair.id} build failed: ${built.error}`);
			const measured = runtimeCall(handle, PORTS, { operation: pair.measure });
			if (measured.success === false) throw new Error(`${pair.id} measure failed: ${measured.error}`);
			holdPairs[pair.id] = measured;
			console.error(`[seed-prep] hold pair ${pair.id}: built=${JSON.stringify(built)} measured=${JSON.stringify(measured)}`);
			const fixture = manifest.fixtures.find(entry => entry.id === pair.id);
			if (!fixture) throw new Error(`manifest is missing fixture ${pair.id}`);
			for (const [key, expected] of Object.entries(fixture.fingerprint)) {
				if (measured[key] !== expected) {
					throw new Error(`${pair.id}.${key} measured ${JSON.stringify(measured[key])}, expected ${JSON.stringify(expected)}`);
				}
			}
		}

		// BELT PADS (Lane B): the belt fixtures return as pads on the two free grid slots (64,22) and
		// (92,22). Physics (an over-packed corner, a jammed loop) are EMERGENT under elapsed ticks, so —
		// like build_census_fusion — the build op only PLACES belts and a JS feed loop runs the sim
		// (sleeps between rounds) until the state settles. Fingerprints are pinned from the SETTLED
		// measured output, never hand-authored.
		const beltPads = {};
		{
			// Corner: 6 east belts feeding a north corner + a north dead-end; feed the entry belt until
			// two consecutive dry rounds (max compression, nothing moving) — the ported recovery recipe.
			const id = "belt-corner-recovery";
			const origin = originOf(id);
			const anchors = anchorsFor(id);
			runtimeCall(handle, PORTS, { operation: "stamp_test_cell", origin_x: origin.x, origin_y: origin.y,
				name: id, rows: TEMPLATE_ROWS, legend: LEGEND, card: cardFor(id) });
			const built = runtimeCall(handle, PORTS, { operation: "build_belt_corner_pad", anchors });
			if (built.success === false) throw new Error(`belt corner build failed: ${built.error}`);
			let fed = 0, stable = 0, rounds = 0;
			while (stable < 2 && rounds < 40) {
				rounds += 1;
				const feed = runtimeCall(handle, PORTS, { operation: "feed_belt_corner", entry: built.entry });
				if (feed.success === false) throw new Error(`belt corner feed failed: ${feed.error}`);
				fed += feed.added;
				if (feed.added === 0) stable += 1; else stable = 0;
				await sleep(600);
			}
			const measured = runtimeCall(handle, PORTS, { operation: "measure_belt_corner_pad", anchors });
			if (measured.success === false) throw new Error(`belt corner measure failed: ${measured.error}`);
			if (!(measured.overpacked >= 1)) throw new Error(`belt corner not over-packed: ${JSON.stringify(measured)}`);
			beltPads[id] = measured;
			console.error(`[seed-prep] belt corner pad: fed=${fed} rounds=${rounds} measured=${JSON.stringify(measured)}`);
		}
		{
			// Loop: 16-belt 5x5 from the shared fixture-layout geometry; feed toward 125 one-item stacks
			// with ticks, then poll until the two-side split is STABLE across 3 reads (a jammed loop).
			const id = "belt-5x5-125-unstacked";
			const origin = originOf(id);
			const anchors = anchorsFor(id);
			const anchor = anchors["turbo-transport-belt"];
			runtimeCall(handle, PORTS, { operation: "stamp_test_cell", origin_x: origin.x, origin_y: origin.y,
				name: id, rows: TEMPLATE_ROWS, legend: LEGEND, card: cardFor(id) });
			const loopBelts = buildFiveByFiveLoop({ x: anchor.x, y: anchor.y });
			const built = runtimeCall(handle, PORTS, { operation: "build_belt_loop_pad", anchors, belts: loopBelts });
			if (built.success === false) throw new Error(`belt loop build failed: ${built.error}`);
			let total = 0, dry = 0, rounds = 0;
			while (total < 125 && dry < 3 && rounds < 200) {
				rounds += 1;
				const feed = runtimeCall(handle, PORTS, { operation: "feed_belt_loop", anchors, target: 125 });
				if (feed.success === false) throw new Error(`belt loop feed failed: ${feed.error}`);
				total = feed.total;
				if (feed.added === 0) dry += 1; else dry = 0;
				await sleep(600);
			}
			let last = null, stable = 0, polls = 0, measured = null;
			while (stable < 3 && polls < 40) {
				polls += 1;
				measured = runtimeCall(handle, PORTS, { operation: "measure_belt_loop_pad", anchors });
				if (measured.success === false) throw new Error(`belt loop measure failed: ${measured.error}`);
				const key = JSON.stringify(measured.lineQuantities);
				if (key === last) stable += 1; else stable = 0;
				last = key;
				await sleep(600);
			}
			if (stable < 3) throw new Error(`belt loop did not jam to a stable split: ${JSON.stringify(measured)}`);
			beltPads[id] = measured;
			console.error(`[seed-prep] belt loop pad: total=${total} rounds=${rounds} measured=${JSON.stringify(measured)}`);
		}
		// Retire the legacy belt-corner platform, then — ONLY after the loop pad measured green above —
		// clear the nauvis belt clutter (the canonical content now lives on the pads).
		const retire = runtimeCall(handle, PORTS, { operation: "retire_belt_platform" });
		console.error(`[seed-prep] retire belt platform: ${JSON.stringify(retire)}`);
		await sleep(2000); // let destroy(0) settle before the census-bearing save
		const nauvisClear = runtimeCall(handle, PORTS, { operation: "clear_nauvis_belt_clutter" });
		console.error(`[seed-prep] clear nauvis belt clutter: ${JSON.stringify(nauvisClear)}`);

		// Walkable grid (owner request 2026-07-19): join the pads to the hub with foundation so a
		// character can physically walk the whole test floor. Idempotent (fills empty-space only).
		const walkways = runtimeCall(handle, PORTS, { operation: "fill_walkways" });
		console.error(`[seed-prep] walkways: ${JSON.stringify(walkways)}`);

		const saveName = "seed-prep-candidate";
		runtimeCall(handle, PORTS, { operation: "save", save_name: saveName });
		const remoteSave = `${REMOTE_ROOT}/saves/${saveName}.zip`;
		await waitForStableSave(options.container, remoteSave);
		docker(["cp", `${options.container}:${remoteSave}`, options.output], { timeout: 180_000 });

		console.log(JSON.stringify({ status: "PASS", candidate: options.output, fingerprint: censusFingerprint, portedFixtures, migrations, holdPairs, beltPads }, null, 2));
	} catch (error) {
		try { console.error(`isolated Factorio tail:\n${tailFactorioLog(handle)}`); } catch { /* launch may have died early */ }
		throw error;
	} finally {
		await teardownIsolatedFactorio(handle, boundaryErrors);
	}
	if (boundaryErrors.length) throw new AggregateError(boundaryErrors, "seed-prep passed but the teardown boundary was not clean");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	main().catch(error => { console.error(error); process.exitCode = 1; });
}
