// Seed-prep: run committed CONSTRUCTION operations against a seed save in the isolated
// Factorio and emit the next candidate save. This is the scripted replacement for hand-curating
// fixtures into the seed (owner decision 2026-07-17): `prior golden source → seed-prep →
// candidate-vN → build-save.mjs bake`, fully reproducible from the repository.
//
// gallery-runtime.lua stays verify-only; all construction lives in seed-prep-ops.lua and runs
// ONLY here — never on the cluster.
//
// Usage:
//   node tests/lab-gallery/seed-prep.mjs --seed docker/seed-data/lab-saves/lab-gallery-source-surface-export-2.0.77.zip \
//     --output /path/candidate-v10.zip [--container surface-export-host-2]

import { existsSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
	docker, launchIsolatedFactorio, runtimeCall, sleep, tailFactorioLog,
	teardownIsolatedFactorio, waitForRuntime, waitForStableSave,
} from "./isolated-factorio.mjs";

const REMOTE_ROOT = "/tmp/surface-export-lab-gallery-seed-prep";
const PORTS = { gamePort: "34976", rconPort: "27976", rconPassword: "seed-prep-only" };
// Plasma must be GENERATED by running the reactor (output writes are engine-rejected — Pitfall #21,
// fusion outputs are engine-managed), so the build polls until the shared segment holds plasma.
const PLASMA_DEADLINE_MS = 120_000;

export function parseArguments(argv) {
	const result = { seed: null, output: null, container: "surface-export-host-2" };
	for (let index = 0; index < argv.length; index += 1) {
		const argument = argv[index];
		if (argument === "--seed") result.seed = argv[++index];
		else if (argument === "--output") result.output = argv[++index];
		else if (argument === "--container") result.container = argv[++index];
		else throw new Error(`unknown argument ${argument}`);
	}
	if (!result.seed) throw new Error("--seed <save.zip> is required");
	if (!result.output) throw new Error("--output <candidate.zip> is required");
	if (!/^surface-export-host-\d+$/.test(result.container)) throw new Error(`unsupported container ${result.container}`);
	return result;
}

async function main() {
	const options = parseArguments(process.argv.slice(2));
	if (!existsSync(options.seed)) throw new Error(`seed does not exist: ${options.seed}`);
	if (existsSync(options.output)) throw new Error(`refusing to overwrite ${options.output}`);

	const opsLua = fileURLToPath(new URL("./seed-prep-ops.lua", import.meta.url));
	const driver = fileURLToPath(new URL("./runtime-driver.cjs", import.meta.url));
	const config = fileURLToPath(new URL("./seed-prep-config.ini", import.meta.url));

	const handle = launchIsolatedFactorio({
		container: options.container, remoteRoot: REMOTE_ROOT,
		seed: options.seed, config,
		files: [[driver, "runtime-driver.cjs"], [opsLua, "ops.lua"]],
		...PORTS,
	});
	const boundaryErrors = [];
	try {
		await waitForRuntime(handle, PORTS, { operation: "preflight" });
		const built = runtimeCall(handle, PORTS, { operation: "build_census_fusion" });
		console.error(`[seed-prep] built: ${JSON.stringify(built)}`);

		// Phase 1: run until the generator is consuming plasma (flow established).
		const flowDeadline = Date.now() + PLASMA_DEADLINE_MS;
		let reading;
		do {
			await sleep(2_000);
			reading = runtimeCall(handle, PORTS, { operation: "measure_census_fusion" });
			console.error(`[seed-prep] plasma=${reading.plasma_segment} coolant=${reading.coolant} fuel=${reading.fuel_cells} reactor=${reading.reactor_status} generators=${JSON.stringify(reading.generator_status)}`);
		} while (reading.generator_status?.[0] !== "working" && Date.now() < flowDeadline);
		if (reading.generator_status?.[0] !== "working") throw new Error(`generator never reached working: ${JSON.stringify(reading)}`);

		// Phase 2: remove the LOAD (generator stays active-idle) so the reactor fills the shared
		// segment to capacity and parks real stock (the workhorse parks ~10/segment under active
		// flow — live probe 2026-07-18, 2.0.77), then wait for it.
		runtimeCall(handle, PORTS, { operation: "park_census_fusion" });
		const parkDeadline = Date.now() + PLASMA_DEADLINE_MS;
		do {
			await sleep(2_000);
			reading = runtimeCall(handle, PORTS, { operation: "measure_census_fusion" });
			console.error(`[seed-prep] parked plasma=${reading.plasma_segment} reactor=${reading.reactor_status}`);
		} while (reading.plasma_segment <= 0 && Date.now() < parkDeadline);
		if (reading.plasma_segment <= 0) throw new Error("no plasma parked in the shared segment before the deadline");

		const fingerprint = runtimeCall(handle, PORTS, { operation: "freeze_census_fusion" });
		if (fingerprint.all_frozen !== true || fingerprint.all_indestructible !== true) {
			throw new Error(`freeze incomplete: ${JSON.stringify(fingerprint)}`);
		}
		if (fingerprint.reactor_plasma_seg_visible !== true || fingerprint.generator_plasma_seg_nil !== true) {
			throw new Error(`segment-visibility invariant not reproduced: ${JSON.stringify(fingerprint)}`);
		}

		const saveName = "seed-prep-candidate";
		runtimeCall(handle, PORTS, { operation: "save", save_name: saveName });
		const remoteSave = `${REMOTE_ROOT}/saves/${saveName}.zip`;
		await waitForStableSave(options.container, remoteSave);
		docker(["cp", `${options.container}:${remoteSave}`, options.output], { timeout: 180_000 });

		console.log(JSON.stringify({ status: "PASS", candidate: options.output, fingerprint }, null, 2));
	} catch (error) {
		try { console.error(`isolated Factorio tail:\n${tailFactorioLog(handle)}`); } catch { /* launch may have died early */ }
		throw error;
	} finally {
		await teardownIsolatedFactorio(handle, boundaryErrors);
	}
	if (boundaryErrors.length) throw new AggregateError(boundaryErrors, "seed-prep passed but the teardown boundary was not clean");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	main().catch(error => { console.error(error); process.exitCode = 1; });
}
